name = "relay"
compatibility_date = "2025-01-15"

[build]
command = "cd web && npm ci && npm run build"
cwd = "."
watch_dir = "web/src"

[assets]
directory = "web/dist"
not_found_handling = "single-page-application"